# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-14 18:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhlGameStat',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id игры')),
                ('fp_ft_shot', models.IntegerField(default=0, verbose_name='Броски по воротам первой команды в первом периоде')),
                ('fp_ft_reflected', models.IntegerField(default=0, verbose_name='Отбитые броски первой команды в первом периоде')),
                ('sp_ft_shot', models.IntegerField(default=0, verbose_name='Броски по воротам первой команды во втором периоде')),
                ('sp_ft_reflected', models.IntegerField(default=0, verbose_name='Отбитые броски первой команды во втором периоде')),
                ('tp_ft_shot', models.IntegerField(default=0, verbose_name='Броски по воротам первой команды в третьем периоде')),
                ('tp_ft_reflected', models.IntegerField(default=0, verbose_name='Отбитые броски первой команды в третьем периоде')),
                ('fp_st_shot', models.IntegerField(default=0, verbose_name='Броски по воротам второй команды в первом периоде')),
                ('fp_st_reflected', models.IntegerField(default=0, verbose_name='Отбитые броски второй команды в первом периоде')),
                ('sp_st_shot', models.IntegerField(default=0, verbose_name='Броски по воротам второй команды во втором периоде')),
                ('sp_st_reflected', models.IntegerField(default=0, verbose_name='Отбитые броски второй команды во втором периоде')),
                ('tp_st_shot', models.IntegerField(default=0, verbose_name='Броски по воротам третьей команды в третьем периоде')),
                ('tp_st_reflected', models.IntegerField(default=0, verbose_name='Отбитые броски третьей команды в третьем периоде')),
                ('game_data', models.DateField(default=datetime.date.today, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Статистика по игре КХЛ',
                'verbose_name_plural': 'Статистика по играм КХЛ',
            },
        ),
        migrations.CreateModel(
            name='KhlTeam',
            fields=[
                ('team_name', models.CharField(choices=[('Авангард', 'Авангард'), ('Автомобилист', 'Автомобилист'), ('Адмирал', 'Адмирал'), ('Ак Барс', 'Ак Барс'), ('Амур', 'Амур'), ('Барыс', 'Барыс'), ('Витязь', 'Витязь'), ('Динамо Мн', 'Динамо Мн'), ('Динамо Мск', 'Динамо Мск'), ('Динамо Р', 'Динамо Р'), ('Йокерит', 'Йокерит'), ('Куньлунь РС', 'Куньлунь РС'), ('Локомотив', 'Локомотив'), ('Металлург Мг', 'Металлург Мг'), ('Нефтехимик', 'Нефтехимик'), ('Салават Юлаев', 'Салават Юлаев'), ('Северсталь', 'Северсталь'), ('Сибирь', 'Сибирь'), ('СКА', 'СКА'), ('Слован', 'Слован'), ('ХК Сочи', 'ХК Сочи'), ('Спартак', 'Спартак'), ('Торпедо', 'Торпедо'), ('Трактор', 'Трактор'), ('ЦСКА', 'ЦСКА')], help_text='Choose team', max_length=50, primary_key=True, serialize=False, verbose_name='Имя команды')),
            ],
            options={
                'verbose_name': 'Команда КХЛ',
                'verbose_name_plural': 'Команды КХЛ',
            },
        ),
        migrations.CreateModel(
            name='NhlGameStat',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id игры')),
                ('fp_ft_shot', models.IntegerField(default=0, verbose_name='Броски по воротам первой команды в первом периоде')),
                ('fp_ft_reflected', models.IntegerField(default=0, verbose_name='Отбитые броски первой команды в первом периоде')),
                ('sp_ft_shot', models.IntegerField(default=0, verbose_name='Броски по воротам первой команды во втором периоде')),
                ('sp_ft_reflected', models.IntegerField(default=0, verbose_name='Отбитые броски первой команды во втором периоде')),
                ('tp_ft_shot', models.IntegerField(default=0, verbose_name='Броски по воротам первой команды в третьем периоде')),
                ('tp_ft_reflected', models.IntegerField(default=0, verbose_name='Отбитые броски первой команды в третьем периоде')),
                ('fp_st_shot', models.IntegerField(default=0, verbose_name='Броски по воротам второй команды в первом периоде')),
                ('fp_st_reflected', models.IntegerField(default=0, verbose_name='Отбитые броски второй команды в первом периоде')),
                ('sp_st_shot', models.IntegerField(default=0, verbose_name='Броски по воротам второй команды во втором периоде')),
                ('sp_st_reflected', models.IntegerField(default=0, verbose_name='Отбитые броски второй команды во втором периоде')),
                ('tp_st_shot', models.IntegerField(default=0, verbose_name='Броски по воротам третьей команды в третьем периоде')),
                ('tp_st_reflected', models.IntegerField(default=0, verbose_name='Отбитые броски третьей команды в третьем периоде')),
                ('game_data', models.DateField(default=datetime.date.today, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Статистика по игре НХЛ',
                'verbose_name_plural': 'Статистика по играм НХЛ',
            },
        ),
        migrations.CreateModel(
            name='NhlTeam',
            fields=[
                ('team_name', models.CharField(choices=[('Айлендерс', 'Айлендерс'), ('Анахайм Дакс', 'Анахайм Дакс'), ('Аризона', 'Аризона'), ('Баффало', 'Баффало'), ('Бостон', 'Бостон'), ('Ванкувер', 'Ванкувер'), ('Вашингтон', 'Вашингтон'), ('Вегас', 'Вегас'), ('Виннипег', 'Виннипег'), ('Даллас', 'Даллас'), ('Детройт', 'Детройт'), ('Калгари', 'Калгари'), ('Каролина', 'Каролина'), ('Коламбус', 'Коламбус'), ('Колорадо', 'Колорадо'), ('Лос-Анджелес', 'Лос-Анджелес'), ('Миннесота', 'Миннесота'), ('Монреаль', 'Монреаль'), ('Нью-Джерси', 'Нью-Джерси'), ('Нэшвилл', 'Нэшвилл'), ('Оттава', 'Оттава'), ('Пантерс', 'Пантерс'), ('Питтсбург', 'Питтсбург'), ('Рейнджерс', 'Рейнджерс'), ('Сан-Хосе', 'Сан-Хосе'), ('Тампа-Бэй', 'Тампа-Бэй'), ('Торонто', 'Торонто'), ('Филадельфия', 'Филадельфия'), ('Чикаго', 'Чикаго'), ('Эдмонтон', 'Эдмонтон')], help_text='Choose team', max_length=50, primary_key=True, serialize=False, verbose_name='Имя команды')),
            ],
            options={
                'verbose_name': 'Команда НХЛ',
                'verbose_name_plural': 'Команды НХЛ',
            },
        ),
        migrations.AddField(
            model_name='nhlgamestat',
            name='first_team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_team', to='score.NhlTeam', verbose_name='Имя команы'),
        ),
        migrations.AddField(
            model_name='nhlgamestat',
            name='second_team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_team', to='score.NhlTeam', verbose_name='Имя команы'),
        ),
        migrations.AddField(
            model_name='khlgamestat',
            name='first_team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_team', to='score.KhlTeam', verbose_name='Имя команы'),
        ),
        migrations.AddField(
            model_name='khlgamestat',
            name='second_team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_team', to='score.KhlTeam', verbose_name='Имя команы'),
        ),
    ]
